baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Portfolio of Roman Smolkin'


[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
    [menus.main.params]
      class = 'bx bx-home'
    

[[menus.main]]
    name = 'Project-1'
    pageRef = 'project-1'
    weight = 2
    [menus.main.params]
      class = 'bi bi-file-earmark-text'
    

[[menus.main]]
    name = 'Project-2'
    pageRef = '/project-2'
    weight = 3
    [menus.main.params]
      class = 'bi bi-file-earmark-text'
    

[[menus.main]]
    name = 'Project-3'
    pageRef = '/project-3'
    weight = 4
    [menus.main.params]
      class = 'bi bi-file-earmark-text'
    

[[menus.main]]
    name = 'Hire Roman Now!'
    pageRef = '/contact'
    weight = 5
    [menus.main.params]
      class = 'bx bx-envelope'
    
