baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Portfolio of Roman Smolkin'



[[menu.main]]
  name = "Project-1"
  url = "#"
  weight = 2
  [menu.main.params]
    class = 'bi bi-file-earmark-text'

[[menu.main]]
  name = "Details"
  parent = "Project-1"
  url = "/project-1/details/"
  weight = 1

[[menu.main]]
  name = "Details 2"
  parent = "Project-1"
  url = "/project-1/details-2/"
  weight = 2

[[menu.main]]
  name = "Details 3"
  parent = "Project-1"
  url = "/project-1/details-3/"
  weight = 3


[[menu.main]]
  name = "Project-2"
  url = "#"
  weight = 3
  [menu.main.params]
    class = 'bi bi-file-earmark-text'

[[menu.main]]
  name = "Details"
  parent = "Project-2"
  url = "/project-2/details/"
  weight = 1

[[menu.main]]
  name = "Details 2"
  parent = "Project-2"
  url = "/project-2/details-2/"
  weight = 2

[[menu.main]]
  name = "Details 3"
  parent = "Project-2"
  url = "/project-2/details-3/"
  weight = 3

[[menu.main]]
  name = "Project-3"
  url = "#"
  weight = 3
  [menu.main.params]
    class = 'bi bi-file-earmark-text'

[[menu.main]]
  name = "Details"
  parent = "Project-3"
  url = "/project-3/details/"
  weight = 1

[[menu.main]]
  name = "Details 2"
  parent = "Project-3"
  url = "/project-3/details-2/"
  weight = 2

[[menu.main]]
  name = "Details 3"
  parent = "Project-3"
  url = "/project-3/details-3/"
  weight = 3

[[menu.main]]
  name = "Hire Roman Now!"
  url = "/contact"
  weight = 4
  [menu.main.params]
    class = 'bx bx-envelope'
